name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Run build script (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: .github\workflows\build.bat
    
    - name: Run build script (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x .github/workflows/build.sh
        .github/workflows/build.sh
    
    - name: Create Release
      id: create_release
      if: matrix.os == 'ubuntu-latest' # Only create a release from the Ubuntu job
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
  
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ matrix.os == 'windows-latest' && './build/rewst_remote_agent.exe' || './build/rewst_remote_agent' }}
        asset_name: ${{ matrix.os == 'windows-latest' && 'rewst_remote_agent.exe' || 'rewst_remote_agent' }}
        asset_content_type: application/octet-stream
    