name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Run build script (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: .github\workflows\build.bat
    
    - name: Run build script (Ubuntu Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        chmod +x .github/workflows/build.sh
        .github/workflows/build.sh

    - name: Run build script (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x .github/workflows/build.sh
        .github/workflows/build.sh


    - name: Sign Executable (Windows)
      run: |
        $certBytes = [System.Convert]::FromBase64String("$${{ secrets.SELF_SIGNED_CERT }}")
        [System.IO.File]::WriteAllBytes("cert.pfx", $certBytes)
        signtool sign /f cert.pfx /p ${{ secrets.SELF_SIGNED_CERT_PASSWORD }} /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a ./windows-latest-asset/rewst_remote_agent.exe
      if: matrix.os == 'windows-latest'
      shell: pwsh

    - name: Sign Executable (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo ${{ secrets.SELF_SIGNED_CERT }} | base64 --decode > cert.p12
        security create-keychain -p actions my.keychain
        security import cert.p12 -k my.keychain -P ${{ secrets.SELF_SIGNED_CERT_PASSWORD }} -T /usr/bin/codesign
        security list-keychains -s my.keychain
        codesign -s "certificate common name or identity" --keychain my.keychain ./macos-latest-asset/rewst_remote_agent
        security delete-keychain my.keychain

  release:
    needs: build  # This job depends on the 'build' job
    runs-on: ubuntu-latest  # This job only runs on one runner

    steps:
    - name: Bump version and push tag
      id: create_tag
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch # can be one of: major, minor, patch
    
    - name: Create Release
      id: create_release 
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.new_tag }}
        release_name: Release ${{ steps.create_tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Download all assets
      uses: actions/download-artifact@v2

    - name: Upload Release Assets - Windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./windows-latest-asset/rewst_remote_agent.exe
        asset_name: rewst_remote_agent.win.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Assets - Linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./ubuntu-latest-asset/rewst_remote_agent
        asset_name: rewst_remote_agent.linux.bin
        asset_content_type: application/octet-stream
    
    - name: Upload Release Assets - MacOS
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./macos-latest-asset/rewst_remote_agent
        asset_name: rewst_remote_agent.macos.bin
        asset_content_type: application/octet-stream
